version: '3.7'
services:
  fast_api_1:
    build: .
    command: bash -c "pytest && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file: .env
#    volumes:
#      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache

  db:
    image: postgres:12.0-alpine
#    volumes:
#      - postgres_data:/postgresql/'
    ports:
      - "5555:5432"

  cache:
    image: redis:6.2-alpine
#    volumes:
#      - cache:/data
    restart: always
    ports:
      - '6699:6379'

#volumes:
#  postgres_data: